name: Build Congo Genius APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Installer les dépendances
        run: flutter pub get

      - name: Vérifier le projet
        run: flutter analyze

      - name: Compiler l'APK
        run: flutter build apk --release

      - name: Sauvegarder l'APK
        uses: actions/upload-artifact@v4
        with:
          name: congo-genius-apk
          path: build/app/outputs/flutter-apk/app-release.apk
